source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.0'

# Core Rails
gem 'rails', '~> 7.1.0'
gem 'puma', '~> 6.0'
gem 'bootsnap', '>= 1.4.4', require: false

# Database
gem 'pg', '~> 1.5'

# Authentication
gem 'jwt', '~> 2.7'

# CORS
gem 'rack-cors'

# Environment variables
gem 'dotenv-rails', groups: [:development, :test]

# Testing
group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'shoulda-matchers', '~> 6.0'
end

group :development do
  gem 'listen', '~> 3.3'
end

